# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 929ec4bff3e8731c6dd81fd32f7e3812be33c0ed8c5de9f48798e7931e0e1fc56c7f6e9735787a7a6b56e54614e7126e535c9263ae561898cba767a95a104bbb

test:
  secret_key_base: 32ab450f20f932f15520890f04481b0edb34d9b3c0380c36218c5e732f83606db57a5dc6b1cd0332c9c259e5a105919344337b51c640a9a44b8fe526f257e684

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
